Repository ZeGoblyn/WorldOfMusic, pull requests merged in 2022-12, with the labels that each got.

#2 Dev/irthir
  WorldOfMusic/Assets/Resources/FirstPersonTemplate/Prefabs/Character/NestedParent_Unpack.prefab
  WorldOfMusic/Packages/manifest.json
  WorldOfMusic/Packages/packages-lock.json
  WorldOfMusic/UserSettings/Layouts/default-2021.dwlt
Labels: good first issue

#11 Chore/gitignore
  WorldOfMusic/.gitignore
  WorldOfMusic/UserSettings/EditorUserSettings.asset
  WorldOfMusic/UserSettings/HDRPUserSettings.asset
  WorldOfMusic/UserSettings/Layouts/default-2021.dwlt
  WorldOfMusic/UserSettings/Search.settings
Labels: wontfix

#17 Feature/ls blocking scene
  WorldOfMusic/Assets/Scenes/Blocking.meta
  WorldOfMusic/Assets/Scenes/Blocking/zone1.unity
  WorldOfMusic/Assets/Scenes/Blocking/zone1.unity.meta
  WorldOfMusic/Assets/Scenes/Main/World.meta
  WorldOfMusic/Assets/Scenes/Main/World/HUB.meta
  WorldOfMusic/Assets/Scenes/Main/World/HUB/HUB.unity
  WorldOfMusic/Assets/Scenes/Main/World/HUB/HUB.unity.meta
  WorldOfMusic/Assets/Scenes/Main/World/Zone1.meta
  WorldOfMusic/Assets/Scenes/Main/World/Zone1/Zone1.unity
  WorldOfMusic/Assets/Scenes/Main/World/Zone1/Zone1.unity.meta
Labels: leveldesign

#18 Feature/ld blocking hub
  WorldOfMusic/.vscode/settings.json
  WorldOfMusic/Assets/Scenes/Main/World/HUB/HUB.unity
  WorldOfMusic/Packages/manifest.json
  WorldOfMusic/Packages/packages-lock.json
  WorldOfMusic/ProjectSettings/Packages/com.unity.probuilder/Settings.json
Labels: leveldesign
